---
new_page_extension: html
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _articles
  label: Articles
  create: all
  match: "**/*"
- type: directory
  path: _yeasts
  label: Yeasts
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _testimonials
  label: Testimonials
  create: all
  match: "**/*"
- type: directory
  path: _homepageSliders
  label: Homepagesliders
  create: all
  match: "**/*"
- type: directory
  path: _employees
  label: Employees
  create: all
  match: "**/*"
- type: directory
  path: _news
  label: News
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:filename:"
